services:
  - type: web
    name: newoffice2
    env: node
    buildCommand: npm install --include=dev --legacy-peer-deps && cd types && npm install --legacy-peer-deps && cd ../client && npm install --legacy-peer-deps && npm run build && cd .. && npx tsc -p server/tsconfig.server.json
    startCommand: node server-start.js
    envVars:
      - key: NODE_ENV
        value: production
